### ISSUE TITLE
Non-standard moves

### ISSUE THREAD

**Issue by Qwertymine** [kilbith/realchess#2]
There are two legal moves overlooked in your version of chess
1. En-passant
- Where a pawn can take an opposing pawn that is next to it, if it had moved 2 spaces the previous turn, moving as if that pawn had only moved 1 space

2.Castling
- Where the king moves 2 spaces to one side of the board and the rook moves to the other side of the king; This is only legal if neither the king or the affected rook have moved during the game and neither piece or any of the pieces between are in check

En-passant is rarely used, but castling is quite common and should be added if aiming for accuracy

**Comment by kilbith** [comment]
_En-passant_ is indeed rarely used and uncommon, we'll consider the _Castling_ only (quite hard - have to distinguish whether king and rook was touched already).

**Comment by kilbith** [comment]
@beyondlimits Can you look at this, please ?

**Comment by beyondlimits** [comment]
Castling was implemented in d1a6446.
En-passant moves seems to be a hard nut to crack.
