### ISSUE TITLE
Un-doing incorrect moves

### ISSUE THREAD

**Issue by Qwertymine** [kilbith/realchess#3]
There are some moves which under the current system are determined correct, but illegal in real chess.
- Moving a piece when the king is in check - that doesn't resolve the check
- Moving a piece to put the king in check - i.e moving your piece out of a skewer by the opponent
- Moving the king into check

Either there should be more checks on moves, or some method to undo moves, as many players can occasionally make one of these errors

**Comment by kilbith** [comment]
You're expecting too high... there're too many situations where the king can be/is in checkmate and has/has no possibity to survive. This imply a shitload of extra-checkings that are not currently possible with the formspec's framework.

**Comment by Qwertymine** [comment]
I think that the checking would be very possible (assuming the the position of both kings is tracked), however I do agree that this would involve a lot of checks and require a new winning system.
