### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by Qwertymine** [kilbith/realchess#5]
Pawns that are moved to the end of the board should be promoted to a piece of the players choice from the following
- queen
- rook
- knight
- bishop

**Comment by kilbith** [comment]
We'll consider promoting to queen only (and to keep it simple), players are likely to take the most of benefit at this occasion.

**Comment by Hiradur** [comment]
The problem with queen-only promotions is that this could lead to stalemates in certain cases which is why underpromotions exist.
