### ISSUE TITLE
King/Queen cross?

### ISSUE THREAD

**Issue by ghost** [kilbith/realchess#7]
The King usually has the cross on it, but here I noticed it's the queen! :D Also, the en passant was added because pawns originally only moved one square, even on the opening move.

**Comment by kilbith** [comment]
> The King usually has the cross on it, but here I noticed it's the queen!

You're right, will fix that ASAP. Thanks.

**Comment by kilbith** [comment]
https://github.com/kilbith/realchess/commit/269e93d50c5ae2f51b504e7b2f570c3d536c2eca
